### ISSUE TITLE
vim+metals opening a symbol in tvp opens in nerdtree

### ISSUE THREAD

**Issue by svalaskevicius** [scalameta/coc-metals#169]
**Describe the bug**

vim+metals opening a symbol in tvp opens in nerdtree

**To Reproduce** Steps to reproduce the behavior:

1. open nerd tree left of the editor
2. open tvp view (opens left of the nerd tree)
3. find a symbol in tvp and click `r` to open it

**Expected behavior**

the symbol / file would be opened in the editor on the right

**Screenshots**

The middle window was NERDTree before r was pressed on the lower-left side window:

![2020-04-17-182807_3828x2069](https://user-images.githubusercontent.com/893660/79597180-bcae0080-80d9-11ea-9eb9-38703f0c1a37.png)

**Installation:**

- Operating system: Linux
- Vim or nvim version: NVIM v0.4.3
- coc-metals extension version: 8a12eec
- Metals version: "0.8.4"

**Additional context**

**Search terms**

tvp, NerdTree

**Comment by ckipp01** [comment]
Thanks for reporting @svalaskevicius!

So when the TVP panel was first added we had quite a few discussions around whether to automatically close nerdtree if the TVP panel was opened or how to handle it. At the time I only used `netrw` so it wasn't an issue for me, and I was hesitant to code in logic related to nerdtree. I'm still a bit on the fence about it to be honest since we have `netrw` users, [coc-explorer](https://github.com/weirongxu/coc-explorer) users, and [nnn.vim](https://github.com/mcchrish/nnn.vim) users, etc. You get the idea. So I want to avoid coding in logic to account for all of the situations.

All of that to say, I totally get that this isn't a good workflow for nerdtree users, so let me look into this scenario, and hopefully I can at lease like you said filter out the nerdtree buffer and not open the file in there. That should be totally doable.

**Comment by svalaskevicius** [comment]
Yeah, I don't really mind it not closing nerdtree when tvp opens, in fact, that could be seen as unexpected behaviour :)

Some limited awareness about not replacing its contents would be useful though - or at least an injectable config where I could set in my configs so metals would not need to hardcode knowledge about nerd tree (not sure what's achievable though, nor what is the best standard vim-wise here)

**Comment by ckipp01** [comment]
Also, one other thing to note. More than likely the TVP module in coc-metals will be removed in favor if either delegating to the solution that coc.nvim comes up with natively (see [this](https://github.com/neoclide/coc.nvim/issues/1649)), or potentially delegating to [vista](https://github.com/liuchengxu/vista.vim) which is also something I'm looking into.

Overall, these are more advanced than the built-in integration we have.

**Comment by svalaskevicius** [comment]
Nice. I see I have a lot to catchup on in the vimland!  :)

**Comment by ckipp01** [comment]
So this _should_ be fixed in the latest master @svalaskevicius. I'd love to see if that is indeed the case, since I'm not a NERDTree user, so I may have totally missed something. It was a bit of a hack to get around not actually having to code any NERDTree logic into it, but I think it should still work as expected.

I also am aware of how odd it looks when they are open together meaning the TVP panel is super wide. I'm not sure why that's happening, but I'm going to make a ticket to check it out. I also may be changing the default behavior to open it on the right hand side as it seems like most symbol explorers are that way.

**Comment by svalaskevicius** [comment]
Thanks! I'll try it out when I have a minute to update :)
