### ISSUE TITLE
Mixing coc-metals and coc-java

### ISSUE THREAD

**Issue by jqno** [scalameta/coc-metals#183]
**Question**

I have coc-java and coc-metals installed. We use Maven at work for our Scala projects. Whenever I open a Scala file or a Java file, both language servers seem to activate and start building stuff.

Is there a way to prevent coc-metals from running when I'm working on a Java project (and/or coc-java when I'm working on a Scala project)? I think a simple filetype check would suffice for me, I don't work on any mixed projects.

**Installation:**

- Operating system: macOS
- Vim version: 8.1.2400
- coc-metals extension version: 0.8.0
- Metals version: 0.8.4
- coc-java extension version: 1.4.9

**Search terms**

coc-java maven

**Comment by ckipp01** [comment]
Hi @jqno great question. I can only answer from the `coc-metals` side, but what'd I's recommend is that hen you open your Java Maven project you should get prompted by `coc-metals` to import your build. If you select `Don't show again` for that project, it won't import it, won't compile it, and won't really do anything. That should solve your problem with Metals starting in projects you don't want. Let me know if that doesn't work as there is another way to do this, but it's one I like and it requires to be done on a per workspace basis.

**Comment by jqno** [comment]
Hi @ckipp01, thanks for the quick reaction! (And also for your Typelevel talk: the youtube video inspired me to give CoC another shot, I've been using vim-lsc so far.)

I guess your suggestion would indeed work for the Java projects I work on, so I've now also opened an issue at coc-java: https://github.com/neoclide/coc-java/issues/83

In the mean time, I'd still be interested to hear about that other way, just in case coc-java doesn't have a similar solution.

**Comment by ckipp01** [comment]
Thanks! I actually recommend `vim-lsc` to people that just want a very minimal setup, so no complaints from me there.

So the other options is to just disable the plugin on a per-workspace basis.
So instead of `:CocConfig` you could do a `:CocLocalConfig` which creates a config file for that workspace. You could then use this setting to disable `coc-metals`

https://github.com/scalameta/coc-metals/blob/6b6f8305a8215710c145ba0b8323c8e073b861f8/package.json#L69

It would just be set like the following:

```
  "metals.enable": false
```

Then it would just never be started for that workspace. In theory you could do the same with `coc-java` in scala workspaces, but it doesn't look like they have that setting.

The core problem is that both `coc-java` and `coc-metals` have it that if the `pom.xml` is in the workspace, it's an `activationEvent`.

https://github.com/scalameta/coc-metals/blob/6b6f8305a8215710c145ba0b8323c8e073b861f8/package.json#L45

**Comment by ckipp01** [comment]
Also fyi, that feature was just added, and I realized it wasn't in a release yet, so if you do want to try it, make sure you're on `v0.8.1.`.

**Comment by jqno** [comment]
> Thanks! I actually recommend `vim-lsc` to people that just want a very minimal setup, so no complaints from me there.

Oh? I thought in the video you were recommending `vim-lsp`, but maybe I misheard :).

Thanks for telling me about the other option -- that seems like a handy alternative. I hope to hear from the coc-java people soon, hopefully they have a similar feature.

Just for completeness sake, I was thinking, I'm using VimPlug to install `coc-metals` (with `Plug 'scalameta/coc-metals', {'do': 'yarn install --frozen-lockfile'}`). Maybe I can add a `'for': 'scala'` or `'for': 'java'` clause to that. That works for Vim plugins, but I'm not sure if CoC respects that as well. Maybe you can shed some light on that?

**Comment by ckipp01** [comment]
> Oh? I thought in the video you were recommending vim-lsp, but maybe I misheard :).

There is totally a chance I said that 😆. When I was making my slides for Scala UA which was a longer presentation on the same thing I realized I had marked down `vim-lsp` where I meant `vim-lsc`. https://chris-kipp.io/presentations/slides-vim-scala-2020#/

Regarding the `'for': 'scala'` that is actually a great question and I'm not 100% sure. Normally the plugin won't get loaded up if it's not on the desired filetype, but I'm not sure how it works since `coc.nvim` actually loads up the plugin there. If you try this out, please let me know what you discover.

**Comment by jqno** [comment]
Out of curiosity, what makes `vim-lsc` preferable above `vim-lsp` in your opinion?

Anyway, I tried the `'for': 'scala'` thing, and unfortunately, it didn't work. I'll report back if and when I hear something from the `coc-java` people.

**Comment by jqno** [comment]
Looks like `coc-java` has added a new setting `java.enabled` as a result of my query.

**Comment by ckipp01** [comment]
> Out of curiosity, what makes vim-lsc preferable above vim-lsp in your opinion?

Basically, if I want a full experience I'm going to use coc. If I want a minimal experience, I want to only worry about 1 plugin and the basics, which vim-lsc covers for me. In the future, I can see myself just going the built-in LSP support with Nvim.

> Looks like coc-java has added a new setting java.enabled as a result of my query.

Sounds good! So does that basically solve your issue then?

**Comment by jqno** [comment]
Adding the local config indeed stops Metals from starting when I open a Java project, so yeah, issue solved. Thank you!

The new coc-java setting doesn't seem to work, but I'll take that up with them.

**Comment by jqno** [comment]
It looks like the issue with coc-java Joao affects coc-metals: ff you start Vim with an empty buffer, all local settings are ignored until you run `:CocRestart`. See also https://github.com/neoclide/coc-java/issues/83#issuecomment-622313693

Not sure if there's a solution for this yet...

**Comment by ckipp01** [comment]
Hmmm, that's a bit odd that they'd be ignored. Out of curiosity, if you do like `vim .` instead of just `vim` in the directory, I'd assume they are applied?

**Comment by jqno** [comment]
I just tried it out, and, apparently not. Looks like CoC only starts when an actual file is opened, not when netrw is opened instead.

**Comment by jqno** [comment]
It works if I do `vim -c "set ft=scala"`!
