### ISSUE TITLE
UnhandledRejection: Cannot read property 'reader' of undefined

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [scalameta/coc-metals#187]
**Describe the bug**

```
[coc.nvim] error: UnhandledRejection: Cannot read property 'reader' of undefined
TypeError: Cannot read property 'reader' of undefined
    at C:\Users\Oliver\.nvim\plugged\coc.nvim\build\index.js:57558:48
```
when preparing metals.

Using `:CocInstall coc-metals` to install coc-metals. The above error occurs when metals is being prepared.

**Installation:**

- Operating system: Windows
- nvim 0.4.3

**Comment by ckipp01** [comment]
Thanks for reporting @PaperPlaneSoftware.

So I guess I'm not extremely familiar with coc.nvim on windows, but if you're installing with `:CocInstall` it puts everything in your `plugged` directory?

The error doesn't ring any bells of what could be causing this. So first of all try to uninstall and install again, just to make sure this wasn't a fluke. Secondly, could you provide me the version of coc.nvim that you're using?

**Comment by PaperPlaneSoftware** [comment]
So I've reinstalled and that unfortunately didn't help. Same problem.

running :CocInstall coc-metals seems to work fine. I get a message in nvim saying `[coc.nvim] Installed extension: coc-metals`

It's only when I open a scala file that I get the error message.

I'm using coc.nvim version is 0.0.78-bcb2fe977c

I've also looked into the location of the error in index.js. The relevant lines of code are:

```
createConnection() {
    let errorHandler = (error, message, count) => {
        logger.error('connection error:', error, message);
        this.handleConnectionError(error, message, count);
    };
    let closeHandler = () => {
        this.handleConnectionClosed();
    };
    return this.createMessageTransports(this._clientOptions.stdioEncoding || 'utf8').then(transports => {
        return createConnection(transports.reader, transports.writer, errorHandler, closeHandler);
    });
}
```

`transports` is undefined.

**Comment by ckipp01** [comment]
@PaperPlaneSoftware you may want to report this [coc.nvim](https://github.com/neoclide/coc.nvim) repo as the error you are posting is coming from `coc.nvim` rather than `coc-metals`. I did poke around a bit to try to see what could be causing this, but again, I think you should report over there. I didn't realize when you first reported and I asked about the install directory that it was actually coming from `coc.nvim`.

**Comment by PaperPlaneSoftware** [comment]
@ckipp01 yes I think you're right, thanks for the help though.

**Comment by ckipp01** [comment]
Of course. I'll close this for now, but if the issue persists or they point you back here, just let me know.

**Comment by PaperPlaneSoftware** [comment]
@ckipp01 out of interest is it worth me using nvim's new inbuilt language server, or is that not stable enough yet?

**Comment by ckipp01** [comment]
Hey @PaperPlaneSoftware, that's a great question. It _really_ depends on what you're looking for out of your LSP experience. So `coc-metals` and `coc.nvim` try to give you a full experience more similar to what you'll find in VS Code. It's growing crazy fast, has a ton of support, and dedicated plugins. Most of the time, it works. The built-in LSP support of Nnvim is still in nightly, missing features, and has known bugs (especially related to things we need in Metals). So again, it totally depends on what you're looking for.

If you want a stable experience right now that covers the full range of LSP with minimal setup, then stick with coc-metals.

If you just want the basics and are willing to put up with some hiccups getting started and are willing to put in a bit of work, then you can totally go for the built-in. But again, keep in mind that it's changing daily. _If_, you go that route, take a look at [this](https://github.com/ckipp01/nvim-metals). I haven't really talked much about it yet because it's still so new, but it is usable and will guide you throw how to setup the built-in lsp with Metals.

**Comment by PaperPlaneSoftware** [comment]
Awesome! Thanks @ckipp01
