### ISSUE TITLE
Show the scaladoc in the preview floating window while auto-completion

### ISSUE THREAD

**Issue by fspillner** [scalameta/coc-metals#188]
Hi.

First thank you for the great coc extension.

What I'm still missing is the display of the scaladoc of the selected
method while cycling through the suggestions of the auto-completion.

I would love to read the scaladoc of the given method directly
in the preview floating window below the method signature.

The coc-rls (for the Rust) shows beautiful how it can work well.

What do you think?

**Comment by ckipp01** [comment]
Hey @fspillner thanks for the request. I'm not super familiar with coc-rls, but are you able to show me a gif or something of this working to get an idea of exactly how it's displaying? There may actually be an easy way to do this, so I'm open to looking in to it.

**Comment by fspillner** [comment]
Here a screenshot how it could look.

![Screenshot_2020-04-30_10-14-47](https://user-images.githubusercontent.com/468706/80688040-830ec980-8acb-11ea-8fa2-719311a686b7.png)

**Comment by ckipp01** [comment]
Thanks @fspillner. So a couple observations right away. I tried this out just to see if what we needed is there. Take a really simple example like below:

```scala
  /**
    * This is a test 
    *
    * @param a
    */
  final case class Bar(a: Int) extends Foo
```
If I try to complete `Bar` I'd _assume_ that it'd know about the scaladoc. There is a field in LSP specifically for this that Metals does use, `Documentation` in a `CompletionItem`. However, when I look at what is coming back from the server in the examle above, it doesn't contain it.

```json
[Trace - 02:55:41 PM] Sending response 'textDocument/completion - (10)'. Processing request took 82ms
Result: {
  "isIncomplete": true,
  "items": [
    {
      "label": "Bar example.Hello",
      "kind": 9,
      "detail": " example.Hello",
      "preselect": true,
      "sortText": "00000",
      "filterText": "Bar",
      "insertTextFormat": 2,
      "textEdit": {
        "range": {
          "start": {
            "line": 19,
            "character": 2
          },
          "end": {
            "line": 19,
            "character": 4
          }
        },
        "newText": "Bar"
      },
      "data": {
        "symbol": "example/Hello.Bar.",
        "target": "file:/Users/ckipp/Documents/scala-workspace/metals-minimal-sbt/?id\u003droot"
      }
    }
  ]
}
```

So I guess before I can really answer your question I need to figure out why for example we aren't actually getting the documentation for a completion like this. Then once we do have the documentation, we can see how we may be able to display it. I know `coc.nvim` does provide some of this out of the box since if you do a `parameterHint` on the above example it actually shows the scaladoc.

**Comment by fspillner** [comment]
I've checked VSCode and it seems the auto-completion shows the scaladoc of the methods. But it didn't work when trying to auto-complete my methods. Very strange. See in action:

![VSCode-autocompletion-scaladoc-2020-05-01 21-41](https://user-images.githubusercontent.com/468706/80836479-1ee82480-8bf5-11ea-888f-b25ccf6227e7.gif)

**Comment by ckipp01** [comment]
So, I finally figured this out today. I'm a bit embarrassed by how long this took me, and it was completely my fault. 🥳 

To put a little language to it, what we were missing was a [`completionItem/resolve`](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion) call, which is slightly different than the normal `completion` calls to the server. Mainly it takes a bit more time to compute the docs, so it's not done by default. So after the actual completion items are generated, if you want further information, a `completionItem/resolve` request is also sent. I _could not_ figure out why that wasn't happening for coc-metals, and it was odd that even on the `initialize`, it was sending in `completionProvider.resolveProvider: false`. This in turn caused the `completionItem/resolve` requests to never fire. The reason for this is because of the following:

```diff
  const initializationOptions: MetalsInitializationOptions = {
    compilerOptions: {
      completionCommand: "editor.action.triggerSuggest",
      - isCompletionItemResolve: false,
      overrideDefFormat: "unicode",
      parameterHintsCommand: "editor.action.triggerParameterHints",
    }
...
It's super obvious after seeing it, but the `isCompletionItemResolve` being set to false here was basically telling metals we didn't want documentation because we don't handle `completionItem/resolve`. It's a total oversight that this was even in there, and to be honest, it has been part of the `defaults` for coc.nvim when we added them into Metals, and then they were carried over here when we migrated over to fully configuring via `initializationOptions`. Anyways, removing it fixes the issue and finally shows the docs as you would expect. It was just merge in, so give it a try, and let me know if you find any more issues.
