### ISSUE TITLE
`root_patterns` not correctly being recognized

### ISSUE THREAD

**Issue by yz-ark7** [scalameta/coc-metals#220]
**Describe the bug**

I have a workspace which has the following structure:

```
  root
  |- projects
  |   |- project1
  |      - src/scala/some.scala
  |      - build.sbt
  - build.sbt

```
When I use vim to open the `some.scala`, the plugin uses `projects/project1` as the workspace folder and creates `.metals` under `projects/project1`. But it causes library loading failure due to the common settings that are specified in the `root/build.sbt`.

VSCode open the project correctly and generate `.metals` directory under `root` directory.

**Expected behavior**

Open root as the workspace.

**Installation:**

- Operating system: macOS
- Vim or nvim version: NVIM v0.4.3
- coc.nvim version:0.0.78-0c973a7a47
- coc-metals extension version:
- Metals version: (`:CocConfig` to open settings)

**Comment by ckipp01** [comment]
Hi, thanks for the report!

So first of all, the vscode works fine because it has native concept of workspaces, but in Vim/Nvim, there isn't. So to make up for that `coc.nvim` has a `coc_root_pattterns` setting that needs to be filled out in order for it to basically fake what the root of your workspace is by detecting specific files. You can see more about this if you `:h coc_root_patterns`.

However, `coc-metal` already provides the necessary defaults for these, and I just tried the aboe (since I use a similiar setup at work), and it didn't have any issues recognizing the correct workspace. Can you also provide the `coc-metals` version and Metals version that you're using?

Also, are you able to reproduce this in a minimal example that I can try it out on?

**Comment by astefanich** [comment]
Hello,
I'm a user (big fan)/potential future contributor. I'd like to ask you about the behavior you've mentioned above. Metals seems to create a .metals directory in the directory from which the `nvim` command was launched. I.e. if I'm in src/main/scala and I `nvim whatever.scala` metals will create a directory in src/main/scala since that's where I am. If I'm in project root and a I `nvim src/main/scala/whatever.scala`, the directory is created in the project root. Is this correct?

It's typically not a problem, but it might convenient if the process somehow walks up parent directories looking for a pre-existing metals directory. Thoughts on that? Often I'm navigating in and out of files/nvim instances, so if I make direct edits to scala files from their directory, I end up with a number metals directories all over.

I've also noticed that the behavior as described by OP is replicated by using [vim-startify](https://github.com/mhinz/vim-startify). Launching nvim and jumping into a file from this plugin seems to auto change the directory, even if `noautochdir` is set. This is not a coc-metals issue, but I'm just curious anyone uses this and has this issue.

**Comment by ckipp01** [comment]
So I'm actually seeing different behavior on two different repos that I'm testing on, and it's different than what it used to be as well 🤔. So in theory, the example you give @astefanich of opening up `nvim src/main/scala/whatever.scala` should create a `.metals` directory at the root in the directory you actually issued the command from. Not necessarily because you opened the command there, but because it does just as you mentioned, it traverses looking for the root patterns given by the global settings, buffer, or server. You can see this if you `:echo coc#util#root_patterns()`, and you'll see what is given for each.

I have an example repo [here](https://github.com/ckipp01/metals-minimal-sbt), and when I actually cd into `example` and directly open up `nvim Hello.scala`, it correctly find the root of the workspace, and works as expected. Are you able to clone this and verify that it works the same for you?

The odd part is that I have another repo that is very similar, but when I do the same, and do `nvim Hello.scala`, I get a `.metals/` directory in the `example` directory, which will not work. I can't figure out what is different in the two scenarios, but am trying to hunt it down.

**Comment by ckipp01** [comment]
Actually, it appears that the `root_patters` that the server is provided aren't being taken into account correctly. I've open an issue in `coc.nvim` with all of the details. https://github.com/neoclide/coc.nvim/issues/2001

**Comment by yz-ark7** [comment]
What I discovered matches what you guys said: the root directory is determined by the first file nvim opens. If vim launches with the parent directory's scala/sbt files, then it's correct. If it starts with the subproject's scala/sbt files, then the problem reproduced, regardless there is one more .sbt between the CWD and the scala file. It looks like it's an issue with COC calculating the workspace. At least the easy workaround now is to always open the root sbt file.  Thanks, guys!

**Comment by chemzqm** [comment]
It's expected since you have `build.sbt` in project1 and coc.nvim checks cwd first, you have to start vim in your root https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

**Comment by ckipp01** [comment]
> It's expected since you have build.sbt in project1 and coc.nvim checks cwd first, you have to start vim in your root neoclide/coc.nvim/wiki/Using-workspaceFolders

Well there are really two separate issues here. The first one that @yz-ark7 outlined, but then also the other problem that is outlined by @astefanich. The one outline by @astefanich is the one I submitted here: https://github.com/neoclide/coc.nvim/issues/2001

**Comment by yz-ark7** [comment]
I was in the root opening `vim projects/project1/build.sbt` and encountered the problem. If coc.nvim checks cwd first, then the workspace should be the `root`, right?

**Comment by chemzqm** [comment]
> I was in the root opening `vim projects/project1/build.sbt` and encountered the problem. If coc.nvim checks cwd first, then the workspace should be the `root`, right?

But filetype `sbt` is not specified in package.json of coc-metals.
It works as expected for me when opening scale files

**Comment by yz-ark7** [comment]
Sorry, by `build.sbt` I actually mean scala file, I have `au BufRead,BufNewFile *.sbt set filetype=scala`.

**Comment by ckipp01** [comment]
@yz-ark7 I mimicked the situation you have [here](https://github.com/ckipp01/multiple-build-file-example), and when I do like you did, `nvim core/src/main/scala/example/Hello.scala`, it does find the correct root and not the `build.sbt` file that is in core. Does it behave the same for you?

**Comment by yz-ark7** [comment]
Interesting, I have tried both @ckipp01 's repo and my repo, it's actually all GOOD. No matter which files I opened, it's always created `.bloop` and `.metas` in the root directory. ;-)

There are two possibilities that I can think of: 1) I was using scala 2.11.12 yesterday (gcp defaults to that version) and upgraded to 2.12 today; 2) I've updated coc and extensions today.

Well, thanks @ckipp01 and @chemzqm for jumping in so quickly. Appreciate it. Now, my issue should be good to close.

**Comment by ckipp01** [comment]
Glad you got it working out @yz-ark7. I'm going to leave this open though since the issue that @astefanich mentioned still exists, and it looks like the issue was reproduced.

> Reproduced. When getRootPatterns, extensions are not inited, did not set contributes.rootPatterns to workspace.rootPatterns, so build.sbt patterns doesn't exist.

So hopefully this will get fixed so that when the init happens, that the build.sbt will correctly be recognized.

**Comment by ckipp01** [comment]
As of [this](https://github.com/neoclide/coc.nvim/commit/d992e129997d9bda225a4e59ed5e5a57fca1896a) the `root_patterns` issues seems to be fixed, but you'll need to use the latest master of coc.nvim to get the changes.
