### ISSUE TITLE
Make function argument doc pum show up

### ISSUE THREAD

**Issue by siers** [scalameta/coc-metals#264]
**Describe the bug**

1. If you're editing function's arguments, then the argument documentation pum doesn't show up.
2. If you're editing a function and you insert a newline, then it also disappears.

**To Reproduce** Steps to reproduce the behavior:

Edit function's arguments. You can make it appear by reinserting the opening parenthesis and moving around without exiting insert mode, however. Is this intended?

**Expected behavior**

You should be able to make pum visible again, probably without rewriting the parenthesis and walking around in insert mode. Newline shouldn't close it either.

**Screenshots**

**Installation:**

- Operating system: macOS/Windows/Linux
- Vim or nvim version: nvim v0.4.3
- coc.nvim version: 0.0.78
- coc-metals extension version: 0.9.0
- Metals version: (`:CocConfig` to open settings)

**Additional context**

**Search terms**

**Comment by ckipp01** [comment]
Thanks a lot for report @siers! I haven't looked a ton into this before so I was happy to be able to dive in a bit. As far as I can tell, there seems to be something funky going on with coc.nvim when working with the `textDocument/signatureHelp`.

So a couple of things. Firstly, this is all reliant on `textDocument/signatureHelp` requests being sent to metals at the correct times in order for the server to correctly respond with both the general information that should be displayed in the pum, but then also where the underline should be etc.

For example, this works fine if you're just using a method straight:

![2020-07-23 14 48 58](https://user-images.githubusercontent.com/13974112/88288180-af656b00-ccf3-11ea-8bfe-6f8098fa373a.gif)

However, right away you can probably see the issue that the underline is never updated. After the `,` another `textDocument/signatureHelp` request should be sent to the server, but none is. You actually see the same exact think happen when you hit enter like you mentioned.

![2020-07-23 14 50 22](https://user-images.githubusercontent.com/13974112/88288332-ea679e80-ccf3-11ea-83bb-86d8cf5d92c9.gif)

For example, in VS Code, after enter is hit, another request is sent, and everything works as expected. Regarding the leaving then coming back in, this currently doesn't seem to work at all. However, it also doesn't seem to work with other editors like VS Code either. I imagine that's a bit trickier case.

I did take a look at another coc extension, coc-tsserver, since I noticed that when calling a JS function this seemed to work as expected and multiple requests were sent. However, it looks like they have some [custom logic](https://github.com/neoclide/coc-tsserver/blob/d5d4be5aa16cd4401137afd5077777a40d090fa5/src/server/features/signatureHelp.ts) in the extension to make this happen. Ideally, I don't think this should be necessary for every server to implement, since they logic should be pretty identical for various languages with function parameters. I've reached out to them on Gitter to see if I can get some more info, and then I'll report back.

**Comment by ckipp01** [comment]
So I was able to find one large improvement that should help a lot with both keeping the pum up while typing, but also allowing you to enter a parameter or two, leave, and then come back in and see it again. The small change is here https://github.com/scalameta/metals/pull/1944

![2020-07-23 15 56 29](https://user-images.githubusercontent.com/13974112/88294996-26533180-ccfd-11ea-8d89-52ff489b94d0.gif)

**Comment by ckipp01** [comment]
@siers This  was just merged into Metals, so when you get a chance try out the latest snapshot and see if you have a better experience.
