### ISSUE TITLE
Mixing coc-java and coc-metals

### ISSUE THREAD

**Issue by aprimadi** [scalameta/coc-metals#299]
**Question**

I'm working on a project that has mixed Scala and Java codes. `coc-metals` works awesome until I install `coc-java` in which case the `coc-metals` go to definition doesn't seem to work anymore. Is there any way to use both `coc-metals` and `coc-java` in the same project?

**Installation:**

- Operating system: macOS
- nvim version: v0.5.0-650-g4bcf54478
- coc.nvim version: 0.0.78-9f9d8a32c4
- coc-metals extension version:
- Metals version: 0.9.3

**Comment by ckipp01** [comment]
Hey @aprimadi, that's a great question. So it's a bit tricky because once you enter into Javaland, then as you experienced `coc-java` takes over, so then you're fully reliant on it. However, when you switch back to your Scala sources, `coc-metals` should again take over. I'm assuming with you saying that go to definition stops working, that's not the case for you? In the scenario you mention, if you switch to a Java source, and then back to a Scala source and try to utilize any Metals features, do you see anything weird in your `.metals/metals.log` file?

In a perfect world there would actually be some interop with going on at the server level, [there is a feature request here for it](https://github.com/scalameta/metals-feature-requests/issues/5), but that will be no small task.

**Comment by ckipp01** [comment]
Let me know if you have any other questions about this, but I'm going to go ahead and close this.
