### ISSUE TITLE
Initial prompt position

### ISSUE THREAD

**Issue by jrzhang12** [scalameta/coc-metals#314]
@**Question**

How to get the initial prompt shown at the bottom like the example in the readme
**Screenshots**

mine: 
![image](https://user-images.githubusercontent.com/41531801/95805587-c05ec080-0cd3-11eb-9ec9-40ac608dc0cc.png)

expected:
![image](https://user-images.githubusercontent.com/41531801/95805600-c94f9200-0cd3-11eb-8767-3f055f1a51cd.png)

**Installation:**
- Operating system: macOS
- nvim version: 0.4.4
- coc.nvim version: 0.0.79
- coc-metals extension version: 0.9.5
- Metals version: (`:CocConfig` to open settings)

**Additional context**

**Search terms**
scala metals prompt

**Comment by ckipp01** [comment]
Hey @jrzhang12, thanks for the question! This was actually a recent change done in `coc.nvim`. You'll find two recently new settings in your coc config:

```
  "coc.preferences.promptInput": false, // <-- this one is the float for renames etc
  "coc.preferences.floatQuickpick": false, // <-- this one is the float for quick selects
```

Turning those both to false will give you the behavior like you see in the screenshots. I haven't updated them yet since this behavior is only default for those using newer versions of Vim or Neovim, but will in the future.
