### ISSUE TITLE
Jump to definition in Scaladoc

### ISSUE THREAD

**Issue by vito-c** [scalameta/coc-metals#315]
I would like to be able to use jump to definition on a scala doc for example:

```
[[ com.some.package.MyClass#coolMethod ]]
```

I was wondering if this is already possible and I just had something mis configured? 

My follow up question: How can I pass a string to `coc` to execute the look up?
```
CocActionAsync('jumpDefinition')
```

```
CocActionAsync({action}, [...{args}, [{callback}]])

	Call CocAction without blocking vim.

	Optional callback is called with `error` as the first argument and
	`response` as the second argument.
```

I'm not sure what the underlying method call would be. Thanks!

**Comment by ckipp01** [comment]
Hey, @vito-c! Regarding the jump to definition on the scaladoc, that's currently not available. I don't know of a feature request for it either, so it'd be a good one to add to the [metals-feature-request repo](https://github.com/scalameta/metals-feature-requests/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

Regarding the way to pass something into the `CocActionAsync('jumpDefinition')`, I'm actually unsure. As you pointed out, the docs don't really explain what `args` can be. I looked at the actual definition of the function, which can be found [here](https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim#L77), and followed it a bit, but it still wasn't clear without really doing a deep dive. I'd recommend asking in their gitter channel as they might have a better idea. Out of curiosity, what would you like to pass to it? A symbol, or a cursor location? I'm pretty sure that the internals of coc.nvim actually just look at the position under the cursor when it receives the request, and then forwards the location to the server. So I'm not sure if it will be possible to pass in a symbol if that's what you're attempting.

**Comment by vito-c** [comment]
The reason I wanted to be able to call this function explicitly is because I  was thinking about some features I might want to add for myself.  Maybe the `jumpDefinition` is a bad example. Something I do like to do is add the type information to a variable (I think  there is a way to do this in scalafmt?).  So I will hover on the variable  `k` and then yank/paste the type info. I was going to make a little scirpt to automate that...

I also wanted to make a little script to add arguments to case classes for example
```scala
case class Foo(a:Int, b:String)
val foo = Foo(1,"str")
// then convert that to
// val foo = Foo( a = 1, b = "str")
```
Just an example of  some things.

**Comment by ckipp01** [comment]
Gotcha, that makes sense. As for the use case of adding type information, as you said, that's something that you can do currently with public members using [Scalafix](https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes.html). We also have a feature request to integrate it into Metals here: https://github.com/scalameta/metals-feature-requests/issues/58.

Recently a pr was merged in to show synthetics as well, so either the inferred result type or implicits for example. For editors taht support inline virtual text, it will show up in line, but for coc-metals, since only nvim supports virtual text, and only at the end of the line, it will actually show up as another section in the hover under "With synthetics".

Depending on how you'd like to go about implementing some of this stuff, it may be worth maybe trying to implement it in Metals itself to benefit other editors, and we'd happily try to provide some guidance if you want.

I see that you did end up creating a feature request for the goto-definition on scaladocs, so I'm going to go ahead and close this.
