### ISSUE TITLE
Worksheet Request

### ISSUE THREAD

**Issue by vito-c** [scalameta/coc-metals#324]
When I am working on a worksheet sometimes I don't care about values. I just want to work with types. So I  might do something like:
```scala
val foo:  Either[String, Future[Int]] = ???
```
but in the worksheet that  gives:
```
[mdoc] [E] scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:230)
	at repl.MdocSession$App.<init>(sso.worksheet.sc:23)
	at repl.MdocSession$.app(sso.worksheet.sc:3)
```
Is that expected? Would there be a way to have a worksheet that only deals with types?
Thanks

**Comment by ckipp01** [comment]
> Is that expected? 

Thanks for the question @vito-c, so this is intentional. The main point of the worksheet is indeed to actually get and see the evaluation. So as you can see from the diagnostic, mdoc doesn't allow `foo` to be unbound. It'd be interesting to think about having some type of _playground_ that allows this, but with mdoc afaik, it's not possible right now.

> Would there be a way to have a worksheet that only deals with types?

As for a worksheet that only displays types, it doesn't really exist at the moment. So I guess you could create a feature request for it.

**Comment by vito-c** [comment]
would I crate the request here? or in another repo?

**Comment by ckipp01** [comment]
Since it's not specific to the extension, create it in the [metals-feature-requests repo](https://github.com/scalameta/metals-feature-requests).
