### ISSUE TITLE
Weird syntax highlighting on "go to..."

### ISSUE THREAD

**Issue by jpalus** [scalameta/coc-metals#336]
If I edit files directly syntax highlighting works perfectly fine in every scala file, however if I use "go to declaration" or "go to symbol" syntax highlighting is weird... it's partial. Parts of file are highlighted but most of it is not. After reloading file with ":e" highlighting is fine again. Initially I wanted to raise it to coc.nvim team however I cannot reproduce it with neither coc-java nor coc-clangd. Only metals.

Sample after going to ActorRefProvider.actorOf():

![image](https://user-images.githubusercontent.com/484155/97776878-2cfb0b80-1b6c-11eb-9406-07a06a55f3ec.png)

Same source after ":e":

![image](https://user-images.githubusercontent.com/484155/97776888-3edcae80-1b6c-11eb-872d-0798cdf562b7.png)

Linux
vim 8.2
coc.nvim 0.0.79
coc-metals 0.9.5

**Comment by ckipp01** [comment]
Thanks for reporting @jpalus although this doesn't have anything to do with `coc-metals` or `coc.nvim`, but rather Scala syntax highlight in Vim. Just to clarify, Metals play absolutely no part in anything related to syntax highlighting at the moment. From my understanding this issue is simply that the when quickly jumping between files the syntax highlighting isn't able to correctly read everything, so it ends up thinking there is just long strings, which is why you'll see a huge chunk of the file highlight as if it was just a string.

You can actually mimic this without using `coc.nvim` and just jump around to multiple different Scala files. This probablem is one of the large ones that [tree-sitter](https://tree-sitter.github.io/tree-sitter/) would greatly improve in the Vim ecosystem.
